### ISSUE TITLE
pypi package seems broken?

### ISSUE THREAD

**Issue by simsong** [samapriya/nsfsearch#1]
The pypi package seems broken? 

```
 % pip install nsfsearch
Collecting nsfsearch
  Downloading nsfsearch-0.0.1.tar.gz (4.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/simsong/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/09/8v4pdnys627fqqh3vjbvsnq40000gn/T/pip-install-dslbn2yu/nsfsearch/setup.py'"'"'; __file__='"'"'/private/var/folders/09/8v4pdnys627fqqh3vjbvsnq40000gn/T/pip-install-dslbn2yu/nsfsearch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/09/8v4pdnys627fqqh3vjbvsnq40000gn/T/pip-install-dslbn2yu/nsfsearch/pip-egg-info
         cwd: /private/var/folders/09/8v4pdnys627fqqh3vjbvsnq40000gn/T/pip-install-dslbn2yu/nsfsearch/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/09/8v4pdnys627fqqh3vjbvsnq40000gn/T/pip-install-dslbn2yu/nsfsearch/setup.py", line 10, in <module>
        if StrictVersion(setuptools_version) < StrictVersion('38.3.0'):
      File "/Users/simsong/opt/anaconda3/lib/python3.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/Users/simsong/opt/anaconda3/lib/python3.7/distutils/version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '46.0.0.post20200309'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by samapriya** [comment]
This seems to be an issue related to anaconda only and I just added a continuous integration check for Python 3.6-3.9 for all operating systems and the check seems to succeed. So am not making any operational changes to the codebase for now but thank you for your suggestion
